### ISSUE TITLE
Voronoi plot fails with Value Error: Points cannot contain Nan

### ISSUE THREAD

**Issue by florianjehn** [ResidentMario/geoplot#281]
I am using the voronoi plot function to create a global plot based on a large number of points. With my test data set that only contained the US I had no problems: [Link to figure](https://github.com/florianjehn/Seaweed-Growth-Model/blob/main/results/grid/cluster_spatial_US.png)

However, if I run the same code, but with a larger dataset I get the following error:

```
Traceback (most recent call last):
  File "/home/florian/Documents/GitHub/Seaweed-Growth-Model/src/plotting/plotter_grid.py", line 144, in <module>
    cluster_spatial(growth_df, global_or_US)
  File "/home/florian/Documents/GitHub/Seaweed-Growth-Model/src/plotting/plotter_grid.py", line 58, in cluster_spatial
    ax = gplt.voronoi(growth_df.dropna(), hue="cluster", legend=True, linewidth=0.3)
  File "/home/florian/local/anaconda3/envs/seaweed-growth-model/lib/python3.8/site-packages/geoplot/geoplot.py", line 1594, in voronoi
    return plot.draw()
  File "/home/florian/local/anaconda3/envs/seaweed-growth-model/lib/python3.8/site-packages/geoplot/geoplot.py", line 1559, in draw
    geoms = build_voronoi_polygons(self.df)
  File "/home/florian/local/anaconda3/envs/seaweed-growth-model/lib/python3.8/site-packages/geoplot/ops.py", line 195, in build_voronoi_polygons
    vor = Voronoi(geom)
  File "_qhull.pyx", line 2627, in scipy.spatial._qhull.Voronoi.__init__
  File "_qhull.pyx", line 285, in scipy.spatial._qhull._Qhull.__init__
ValueError: Points cannot contain NaN
```
This even happens when I explicitly dropna before sending the data to the function, so my data cannot contain NaN. Therefore, I guess that this happens somewhere in geoplot. Any ideas?

**Comment by florianjehn** [comment]
Only similar problem I could find is: https://github.com/xinshuoweng/AB3DMOT/issues/32

**Comment by florianjehn** [comment]
The code that produces the function is in the function cluster _spatial in this file: https://github.com/florianjehn/Seaweed-Growth-Model/blob/main/src/plotting/plotter_grid.py

I cannot provide the actual data easily, as it is several hundred MB, but the test dataset is here: https://github.com/florianjehn/Seaweed-Growth-Model/blob/main/data/interim_results/seaweed_growth_rate_clustered_US.pkl

Problem is that the test data set runs just fine, while the actual dataset does not. However, all other plotting with the actual data set works just fine, so I am not sure what's going on .

**Comment by florianjehn** [comment]
Nevermind, that's on me. Just checked some more and it seems that I somehow managed to give some Points an nan for their x value.
